[package]
name = "torben-shim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
torben-contracts = { path = "../torben-contracts" }
torben-core = { path = "../torben-core" }

[lints]
workspace = true
